### ISSUE TITLE
Nested Schemas shown incorrectly in Model Schema in swagger ui

### ISSUE THREAD

**Issue by nickg415** [swagger-api/swagger-js#535]
When working with swagger-ui, I noticed that nested schemas only show the first property in the Model Schema, when I believe it should show the nested schema as an object. I was able to track this down to the schemaToJSON function in swagger-client.js line 2510:

```
} else if (_.isUndefined(schema.items) && _.isArray(schema.enum)) {
```

I added in a console.log statement just before this if conditional:

```
console.log("Schema: ", schema);

if (schema.example) {
  output = schema.example;
}
else if (_.isUndefined(schema.items) && _.isArray(schema.enum)) {
  output = schema.enum[0];
}
```

and got a value of:

```
enum: [
  "property1",
  "property2
]
example: undefined
properties: {
  "property1": { //omitted for brevity },
  "property2": { //omitted for brevity }
}
required: [
  "property1",
  "property2
]
```

So even though this is a nested object, the above conditional would see that the enum property was an array and would just use the first property as a value. In Example, if I have the following Schema:

```
"ModelA" : {
    "description" : "",
    "id" : "ModelA",
    "properties" : {
      "modelB" : {
	"description" : "Some description here...",
	"required" : true,
	"type" : "ModelB"
      }
    }
  },
  "ModelB" : {
    "property1": {
        "required": true,
        "type": "string",
        "description": ""
      },
      "property2": {
        "required": true,
        "type": "string",
        "description": ""
      },
  }
```

then the model Schema would look like this:

```
{
  "modelB" : "property1"
}
```

when I'd expect it to look like this:

```
{
  "modelB" : {
    "property1": "string",
    "property2": "string"
  }
}
```

Not really sure if the enum property should be there or not for nested objects, but the below fix resolves the issue for me:

```
if (schema.example) {
  output = schema.example;
}
else if (_.isUndefined(schema.items) && _.isUndefined(schema.properties) && _.isArray(schema.enum)) {
  output = schema.enum[0];
}
```

Not sure if this is really the issue, or if the issue is further up the chain with the enum property being an array when it shouldn't. If this is the correct fix, I would be happy to contribute a pull request.

**Comment by fehguy** [comment]
Hi, can you please try with the latest, 2.1.1 release?  I believe this was fixed yesterday.

**Comment by nickg415** [comment]
Unless I'm missing something, this is still an issue with the latest release of swagger ui. I pulled down the latest updates from the master branch in the swagger ui project, and copied the dist directory over into my project to test it out. Were the fixes from yesterday included in that dist?

**Comment by fehguy** [comment]
if you see 2.1.1 in your swagger-ui.js then you have the latest.  And if you're still seeing the issue, it's a bug.  Please confirm and i'll get to it.

**Comment by nickg415** [comment]
yep, confirmed I am looking at 2.1.1:

```
/**
 * swagger-ui - Swagger UI is a dependency-free collection of HTML, JavaScript, and CSS assets that dynamically generate beautiful documentation from a Swagger-compliant API
 * @version v2.1.1
 * @link http://swagger.io
 * @license Apache-2.0
 */
```

**Comment by fehguy** [comment]
Thanks for the confirmation

**Comment by fehguy** [comment]
Looks like this is working
